[package]
name = "atomic_slotmap"
version = "1.0.0"
edition = "2018"
authors = ["Dawid Szostak <szostid@gmail.com>"]
description = "Atomic slotmap data structure"
license = "Zlib"
repository = "https://github.com/szostid/atomic_slotmap"
readme = "README.md"
keywords = [
    "slotmap",
    "storage",
    "allocator",
    "arena",
    "reference",
    "atomic",
    "lockfree",
]
categories = ["data-structures", "memory-management", "caching"]
rust-version = "1.58.0"

[features]
default = ["std"]
unstable = []
std = []

[dependencies]
slotmap = "^1"

[dev-dependencies]
quickcheck = "1.0"
criterion = "0.5"
parking_lot = "0.12"

[build-dependencies]
version_check = "0.9"

[[bench]]
name = "concurrency"
harness = false
